### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by anders-was-here** [jettify/aionsq#2]
From Python 3.7 and on 'asyncio' is a reserved word.

>   asyncio.async(coro_or_future, *, loop=None)
>      A deprecated alias to ensure_future().

 
From: https://docs.python.org/3.5/library/asyncio-task.html#asyncio.async

Solution seem to be:
```
-        asyncio.async(coro(), loop=self.loop)
+        asyncio.ensure_future(coro(), loop=self.loop)

`````

**Comment by jettify** [comment]
Sorry project is no longer maintained.

**Comment by anders-was-here** [comment]
Thank you for the update.
We'll handle it.
